{% set version = "1.1.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-farver
  version: {{ version|replace("-", "_") }}

source:
  fn: farver_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/farver_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/farver/farver_{{ version }}.tar.gz
  sha256: 2086f309135f37705280fe2df851ad91dc886ad8f2a6eb1f3983aa20427f94b6

build:
  merge_build_host: True  # [win]
  number: 1
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('m2w64_cxx') }}        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-rcpp >=0.12.15
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-rcpp >=0.12.15

test:
  commands:
    - $R -e "library('farver')"           # [not win]
    - "\"%R%\" -e \"library('farver')\""  # [win]

about:
  home: https://github.com/thomasp85/farver
  license: MIT
  summary: The encoding of colour can be handled in many different ways, using different colour
    spaces. As different colour spaces have different uses, efficient conversion between
    these representations are important. The  'farver' package provides a set of functions
    that gives access to very fast colour space conversion and comparisons implemented
    in C++, and offers  100-fold speed improvements over the 'convertColor' function
    in the  'grDevices' package.
  license_family: MIT

extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
