# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "t0GW6t1bC4KXgyKhyn7WQUH/Gd9Hy9vJq4s/ehI5k3bRSAXMaYSa/o8GGutP9Rv0zoLAMjOiyNq0VWdjHp4F9WnWxnq2uuvmP7LEHiioFccUnlVN8YCDX5r1vYd07dt82A5qJavDB2OQ8LHSEY5EiLoQtGygZoMPFLR99zdD0nkg/HwNr8c176EWH7kZaMnkFcgu7mBoaqektiDR2ltTJmn5KU/J4mnv1gcFukuJ7/NG4jS52zlvCRO7lWIVIVe8oE39ZlxjLTWv217HLlAnzXldB1mxMPlktw0Ji1U6lGBvdCV+5WQhRMG1RpdLIRaRePBFjGrtqewM+PlyyGEE3hogW/UeQ9FH3h+ANmV1DmQsUdAEBwdyXwqarQFIiyzdAbX0BE3r/7ZNK0kxLBrdGeW1H7wo6Pwpt+6sgGs1XLDSlDXcKVH3b7yj6Bpev0dmbAVVyIM9mTAtlab6/FJnmb7Qw2KqEyuoBIN589Ai9iBipjvnaxIM10xyXu0ZhfjiW7qn6hmzKGRM2vepey0TVW7cfDXY/EI+nmkO7vj1mUEdZMsQ+K57JfL6aabgZfmpUXHE1pRvKzgzgt6QIY8V/HIYfd6mL7x2IZqMA6TEwyK3nCRAmhrNe/+cyth0FQf4pbsxk/UCWdv1A+pGqc5Xuue6IEcy9UnxW5c+N5SKCXI="

matrix:
  include:
    - env: CONFIG=linux_ppc64le_r_base3.6target_platformlinux-ppc64le UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le

    - env: CONFIG=linux_ppc64le_r_base4.0target_platformlinux-ppc64le UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le

script:
  - export CI=travis
  - export GIT_BRANCH="$TRAVIS_BRANCH"


  - if [[ ${PLATFORM} =~ .*linux.* ]]; then ./.scripts/run_docker_build.sh; fi