# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "t0GW6t1bC4KXgyKhyn7WQUH/Gd9Hy9vJq4s/ehI5k3bRSAXMaYSa/o8GGutP9Rv0zoLAMjOiyNq0VWdjHp4F9WnWxnq2uuvmP7LEHiioFccUnlVN8YCDX5r1vYd07dt82A5qJavDB2OQ8LHSEY5EiLoQtGygZoMPFLR99zdD0nkg/HwNr8c176EWH7kZaMnkFcgu7mBoaqektiDR2ltTJmn5KU/J4mnv1gcFukuJ7/NG4jS52zlvCRO7lWIVIVe8oE39ZlxjLTWv217HLlAnzXldB1mxMPlktw0Ji1U6lGBvdCV+5WQhRMG1RpdLIRaRePBFjGrtqewM+PlyyGEE3hogW/UeQ9FH3h+ANmV1DmQsUdAEBwdyXwqarQFIiyzdAbX0BE3r/7ZNK0kxLBrdGeW1H7wo6Pwpt+6sgGs1XLDSlDXcKVH3b7yj6Bpev0dmbAVVyIM9mTAtlab6/FJnmb7Qw2KqEyuoBIN589Ai9iBipjvnaxIM10xyXu0ZhfjiW7qn6hmzKGRM2vepey0TVW7cfDXY/EI+nmkO7vj1mUEdZMsQ+K57JfL6aabgZfmpUXHE1pRvKzgzgt6QIY8V/HIYfd6mL7x2IZqMA6TEwyK3nCRAmhrNe/+cyth0FQf4pbsxk/UCWdv1A+pGqc5Xuue6IEcy9UnxW5c+N5SKCXI="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2 conda-build
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  -  conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml