appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: t0GW6t1bC4KXgyKhyn7WQUH/Gd9Hy9vJq4s/ehI5k3bRSAXMaYSa/o8GGutP9Rv0zoLAMjOiyNq0VWdjHp4F9WnWxnq2uuvmP7LEHiioFccUnlVN8YCDX5r1vYd07dt82A5qJavDB2OQ8LHSEY5EiLoQtGygZoMPFLR99zdD0nkg/HwNr8c176EWH7kZaMnkFcgu7mBoaqektiDR2ltTJmn5KU/J4mnv1gcFukuJ7/NG4jS52zlvCRO7lWIVIVe8oE39ZlxjLTWv217HLlAnzXldB1mxMPlktw0Ji1U6lGBvdCV+5WQhRMG1RpdLIRaRePBFjGrtqewM+PlyyGEE3hogW/UeQ9FH3h+ANmV1DmQsUdAEBwdyXwqarQFIiyzdAbX0BE3r/7ZNK0kxLBrdGeW1H7wo6Pwpt+6sgGs1XLDSlDXcKVH3b7yj6Bpev0dmbAVVyIM9mTAtlab6/FJnmb7Qw2KqEyuoBIN589Ai9iBipjvnaxIM10xyXu0ZhfjiW7qn6hmzKGRM2vepey0TVW7cfDXY/EI+nmkO7vj1mUEdZMsQ+K57JfL6aabgZfmpUXHE1pRvKzgzgt6QIY8V/HIYfd6mL7x2IZqMA6TEwyK3nCRAmhrNe/+cyth0FQf4pbsxk/UCWdv1A+pGqc5Xuue6IEcy9UnxW5c+N5SKCXI=}
